package uga.scraper;
import static java.util.Map.*;

import java.util.Map;
import java.util.Map.Entry;
import java.util.Objects;

public class BuildingMap {
    
    /** Stores the ID and name of most buildings on the Athens campus.
     *  Some rarely used or newly built buidings may be missing. */
    private static final Map<String, String> buildings = Map.ofEntries(
        entry("2029", "529 Baxter St"),
        entry("2635", "1260 S. Lumpkin St."),
        entry("1060", "Aderhold"),
        entry("0631", "Administration Building"),
        entry("2426", "Agronomy Seed Lab Agronomy"),
        entry("2408", "Soil Building"),
        entry("0736", "Amos Hall"),
        entry("1077", "Animal Health Research Center"),
        entry("2119", "Auxiliary Services"),
        entry("2640", "Bank of America Building"),
        entry("0735", "Benson Hall"),
        entry("0050", "Baldwin Hall"),
        entry("1021", "Barrow Hall"),
        entry("1686", "Baseball Maintenance & Storage"),
        entry("1000", "Biological Sciences Building"),
        entry("2264", "Black-Diallo-Miller Hall"),
        entry("2216", "Boggs Hall"),
        entry("1023", "Boyd Research and Education Center"),
        entry("0055", "Brooks Hall"),
        entry("2213", "Brumby Hall"),
        entry("1516", "Building 1516"),
        entry("0110", "Business Services"),
        entry("1671", "Butts-Mehre Heritage Hall"),
        entry("2438", "CAGTECH"),
        entry("0046", "Caldwell Hall"),
        entry("2118", "Campus Mail/Environmental Safety"),
        entry("1637", "Campus Transit Facility"),
        entry("0031", "Candler Hall"),
        entry("2419", "CCRC"),
        entry("2127", "Center for Applied Isotope Study"),
        entry("2395", "Center for Molecular Medicine"),
        entry("0178", "Central Campus Mech. Building"),
        entry("2122", "Central Food Storage"),
        entry("2131", "Ceramics"),
        entry("0022", "Chapel"),
        entry("1001", "Chemistry"),
        entry("1004", "Chemistry Annex"),
        entry("0101", "Chicopee Main Building No.1"),
        entry("1652", "Child Development Laboratory"),
        entry("2215", "Church Hall"),
        entry("0290", "Clark Howell Hall"),
        entry("1687", "Coliseum Training Facility"),
        entry("1070", "College of Veterinary Medicine 1"),
        entry("1011", "Conner Hall"),
        entry("1248", "Consumer Research Center"),
        entry("1043", "Coop. Ext. Serv. - Hoke Smith"),
        entry("0739", "Correll Hall"),
        entry("2627", "Creative Problem Solving Lab"),
        entry("2211", "Creswell Hall"),
        entry("1030", "Dance & Marine Sciences Building"),
        entry("1057", "Davison Life Sciences Complex"),
        entry("1010", "Dawson Hall"),
        entry("0045", "Dean Rusk Hall"),
        entry("0021", "Demosthenian Hall"),
        entry("0044", "Denmark Hall"),
        entry("0741", "District Energy Plant #1"),
        entry("1617", "District Energy Plant #2"),
        entry("0768", "The Athenaeum"),
        entry("1090", "Driftmier Engineering Center"),
        entry("1033", "Ecology"),
        entry("1632", "Electronics Shop"),
        entry("2425", "Entomology Greenhouse/Headhouse"),
        entry("1050", "Environmental Health Sciences"),
        entry("1246", "Family Science Center 1"),
        entry("1249", "Family Science Center 2"),
        entry("0060", "Fine Arts Building"),
        entry("1685", "Foley Baseball Stadium"),
        entry("1022", "Food Processing Lab"),
        entry("1020", "Food Science Building"),
        entry("1040", "Forestry Resources 1"),
        entry("1140", "Forestry Resources 2"),
        entry("1044", "Forestry Resources 3"),
        entry("1046", "Forestry Resources 4"),
        entry("0650", "Founders House"),
        entry("2835", "Four Towers"),
        entry("1002", "Geography and Geology"),
        entry("0090", "Geology Hydrothermal Lab"),
        entry("1512", "George D. Busbee Hall"),
        entry("1910", "George Hall"),
        entry("1640", "Georgia Center for Cont Ed"),
        entry("1693", "Georgia Museum of Art"),
        entry("0640", "Gilbert Hall"),
        entry("2219", "Global Engagement"),
        entry("0756", "Government Relations"),
        entry("1031", "Hardman Hall"),
        entry("2410", "Headhouse Horticulture"),
        entry("2411", "Headhouse Plants Agronomy"),
        entry("2622", "Henry Feild Tennis Stadium"),
        entry("4602", "H.H. Tift Building"),
        entry("2214", "Hill Hall"),
        entry("0043", "Hirsch Hall"),
        entry("1042", "Hoke Smith Annex"),
        entry("0120", "Holmes/Hunter Academic Building"),
        entry("1340", "Horticulture Greenhouse"),
        entry("2423", "Horticulture Greenhouse 1"),
        entry("1247", "Housing Research Center"),
        entry("1911", "Hudson Clinic"),
        entry("1691", "Hugh Hodgson School of Music"),
        entry("0620", "Human Resources"),
        entry("0066", "Instructional Plaza"),
        entry("1131", "Interdisciplinary STEM Research Bldg"),
        entry("0767", "Interior Design Studios "),
        entry("2607", "Intramural Fields"),
        entry("0734", "Ivester Hall"),
        entry("1675", "J.W. Fanning Building"),
        entry("0040", "Jackson Street Building"),
        entry("2680", "Jewelry & Metalwork Art Studio"),
        entry("0250", "Joseph E. Brown Hall"),
        entry("0062", "Journalism Building"),
        entry("2440", "Lake Herrick Pavilion"),
        entry("1694", "Lamar Dodd School of Art"),
        entry("2414", "Lath Greenhouse 3 Botony"),
        entry("0053", "LeConte Hall"),
        entry("2685", "Learning & Development Center"),
        entry("2614", "Learning Ally"),
        entry("2604", "Legion Pool"),
        entry("1058", "Life Sciences Fermentation Lab"),
        entry("2623", "Lindsey Hopkins Indoor Tennis Stad."),
        entry("2208", "Lipscomb Hall"),
        entry("1504", "Livestock Instructional Arena"),
        entry("0054", "Main Library"),
        entry("1221", "Mary Lyndon Hall"),
        entry("1515", "McWhorter Hall"),
        entry("0024", "Meigs Hall"),
        entry("2209", "Mell Hall"),
        entry("0670", "Memorial Hall"),
        entry("1679", "Men's Tennis Clubhouse"),
        entry("0061", "Military Building Army ROTC"),
        entry("0271", "Milledge Hall"),
        entry("1061", "Miller Plant Science"),
        entry("0025", "Moore Hall"),
        entry("0738", "Moore - Rooker Hall"),
        entry("2204", "Morris Hall"),
        entry("1222", "Myers Hall"),
        entry("0030", "New College"),
        entry("0130", "Old College"),
        entry("0737", "Orkin Hall"),
        entry("0056", "Park Hall"),
        entry("1111", "Paul D. Coverdell Center"),
        entry("0270", "Payne Hall"),
        entry("0042", "Peabody Hall"),
        entry("1692", "Performing Arts"),
        entry("1038", "Pharmacy South"),
        entry("0020", "Phi Kappa Hall"),
        entry("1642", "Physical Plant Grounds"),
        entry("1641", "Physical Plant Utility"),
        entry("1003", "Physics Building"),
        entry("1013", "Poultry Science"),
        entry("1025", "Poultry Science Complex"),
        entry("1906", "Pound Hall"),
        entry("0064", "Psychology Building"),
        entry("1041", "R. C. Wilson Pharmacy"),
        entry("1690", "Ramsey Center"),
        entry("0280", "Reed Hall"),
        entry("2417", "Rhizotron Building"),
        entry("1501", "Rhodes Animal Science Center - A"),
        entry("1502", "Rhodes Animal Science Center - B"),
        entry("1503", "Rhodes Animal Science Center - C"),
        entry("2125", "Riverbend Research Lab North"),
        entry("2418", "Riverbend Research Lab South"),
        entry("2124", "Riverbend Solvent Storage Bldg"),
        entry("2639", "River's Crossing Building"),
        entry("1513", "Rooker Hall"),
        entry("2212", "Russell Hall"),
        entry("0740", "Russell Special Collections Building"),
        entry("1215", "Rutherford Hall"),
        entry("0058", "Sanford Hall"),
        entry("0678", "Sanford Stadium"),
        entry("0033", "School of Social Work Building"),
        entry("1035", "Science Learning Center"),
        entry("1621", "Science Library "),
        entry("0124", "Sculpture Canopy"),
        entry("0113", "Small Business Development Center"),
        entry("2409", "Soil Building 2"),
        entry("2437", "Soil Chemical & Equipment Bldg"),
        entry("2413", "Soil Storage Building"),
        entry("1094", "Soil Tillage Laboratory"),
        entry("1220", "Soule Hall"),
        entry("1130", "Statistics & Computer Services"),
        entry("1654", "Stegeman Coliseum"),
        entry("1132", "STEM Research Building"),
        entry("0121", "Spring Street Building"),
        entry("2493", "Strength Building"),
        entry("1673", "Student Athlete Academic Center"),
        entry("4400", "Student Learning Center"),
        entry("0766", "Studio 225"),
        entry("0123", "Tanner Building"),
        entry("0672", "Tate Student Center"),
        entry("0023", "Terrell Hall"),
        entry("2691", "Thomas Street Art Complex"),
        entry("2600", "Thomas Street Art Studio"),
        entry("4897", "Tifton Nespal South"),
        entry("1250", "Tucker Hall"),
        entry("1701", "UGA Health Center"),
        entry("2636", "UGA Real Estate Foundation"),
        entry("1514", "Vandiver Hall"),
        entry("1634", "Vehicle Transporation & Maintenance"),
        entry("1084", "Vet Med Bio Resources"),
        entry("1079", "Vet Med Diagnostic Lab"),
        entry("1064", "Vet. Med Locomotive Diag. Ctr."),
        entry("0041", "Waddel Hall"),
        entry("1082", "Wildlife Health"),
        entry("1678", "Women's Tennis Clubhouse"),
        entry("1912", "Wright Hall"),
        entry("0081", "Zell B. Miller Learning Center")
    );

    public static String getName(String buildingNumber) {
        return buildings.get(buildingNumber);
    }

    public static String getNumber(String buildingName) {
        for (Entry<String, String> entry : buildings.entrySet()) {
            if (Objects.equals(buildingName, entry.getValue())) {
                return entry.getKey();
            }
        }
        return null;
    }
}
